<?php
/**
 * @file
 * This is the module file containing the logic for the creator.
 */

/**
 * Implements hook_menu().
 */
function odsherred_site_creator_menu() {
  $items = array();
  $items['admin/odsherred'] = array(
    'title' => 'Odsherred site creator',
    'access callback' => TRUE,
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/odsherred/sites'),
  );
  $items['admin/odsherred/sites'] = array(
    'title' => 'Odsherred site creators overview',
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('odsherred_site_creator_form'),
    'type' => MENU_DEFAULT_TASK | MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Form callback for creator form.
 */
function odsherred_site_creator_form() {
  $form = array(
    'title' => array(
      '#title' => t('Title'),
      '#description' => t('Descriptive name for the site, for later reference.'),
      '#type' => 'textfield',
    ),
    'url' => array(
      '#title' => t('Url'),
      '#description' => t('Subsite URL, without protocol prefix. ie. <strong>sub1.site.com</strong>'),
      '#type' => 'textfield',
    ),
    'mail' => array(
      '#title' => t('E-mail'),
      '#description' => t('Contact e-mail for the site.'),
      '#type' => 'textfield',
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Save'),
    ),
  );
  return $form;
}

/**
 * Implements hook_FORM_submit().
 */
function odsherred_site_creator_form_submit($form, &$form_state) {
  $queue = 'public://odsherred-creator/queue';
  $complete = 'public://odsherred-creator/complete';
  $failed = 'public://odsherred-creator/failed';
  if (file_prepare_directory($queue, FILE_CREATE_DIRECTORY || FILE_MODIFY_PERMISSIONS) &&
      file_prepare_directory($complete, FILE_CREATE_DIRECTORY || FILE_MODIFY_PERMISSIONS) &&
      file_prepare_directory($failed, FILE_CREATE_DIRECTORY || FILE_MODIFY_PERMISSIONS)) {
    $data = $form_state['values']['title'] . "\n";
    $data .= $form_state['values']['url'] . "\n";
    $data .= $form_state['values']['mail'] . "\n";

    if (file_unmanaged_save_data($data, $queue . '/' . uniqid() . '.txt')) {
      drupal_set_message(t('Site @name queue for creation.', array('@name' => $form_state['values']['title'])), 'status');
    }
    else {
      drupal_set_message('Failed to write file. Check temporary directory setup.', 'error');
    }
  }
  else {
    drupal_set_message('Failed to create site!, check public files directory.', 'error');
  }
}
